blog/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^me/', include('resume.urls')),
    url(r'^contact/', include('contact.urls')),
    url(r'', include('home.urls')),

]

contact/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    
    url(r'', views.post_new, name='post_new'),
   
    
]

home/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    
    url(r'^me/$', views.me, name='me'),
    url(r'^ds/$', views.ds, name='ds'),
    url(r'^mee/$', views.mee, name='mee'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.post_detail, name='post_detail'),
    url(r'^(?P<tag_field>[A-Z]+)/$', views.post_tagdetail, name='post_tagdetail'),
    url(r'^$', views.post_list, name='post_list'),
    
]

resume/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    
    url(r'^me/$', views.me, name='me'),
   
    
]

contact/models.py
from django.db import models
from django.utils import timezone


class Post(models.Model):
    name = models.CharField(max_length=200)
    email_id = models.EmailField(max_length=400)
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True,blank=True, null = True)

home/models.py
from django.db import models
from django.utils import timezone
from ckeditor.fields import RichTextField


class Tag(models.Model):
    title_tag = models.CharField(max_length=100)

    def __unicode__(self):
        return self.title_tag

    def __str__(self):              # __unicode__ on Python 2
        return self.title_tag
        





class Post(models.Model):

    title = models.CharField(max_length=200,blank=True,null =True)
    text = models.TextField(blank=True,null =True)
    author = models.CharField(max_length=400,blank=True,null =True)
    content = RichTextField(blank=True, null = True)
    tag_field = models.ManyToManyField('Tag')


    featured =  models.BooleanField(default = 'False')
    draft =  models.BooleanField(default = 'False')


    




    created = models.DateTimeField(auto_now_add=True,blank=True, null = True)
    modified = models.DateTimeField(auto_now=True,blank=True, null = True)

resume/models.py
from django.db import models

# Create your models here.

contact/forms.py
from django import forms

from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('name', 'email_id','text')

home/forms.py
from django import forms

from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ()

contact/views.py
from django.shortcuts import render

from .forms import PostForm

def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            
    else:
        form = PostForm()
    return render(request, 'contact/contact.html', {'form': form})

home/views.py
from django.shortcuts import render
from .models import Post,Tag
from django.shortcuts import render, get_object_or_404
from .forms import PostForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render
from django.db.models import Q
from django.core.mail import send_mail


def me(request):
    # send_mail('CONTACT PAGE SEARCHED', 'HELLLO .', 'sarthak221995@gmail.com',['sarthak221995@gmail.com'], fail_silently=False)
    return render(request, 'home/me.html', {})


def ds(request):
    return render(request, 'home/ds.html', {})



def mee(request):
    email = request.POST.get('email')
    message = request.POST.get('message')
    subject = "Contact Notification from "
    body = "EMAIL: "+email+"\nMessage: "+message
    send_mail(subject, message, email,['sarthak221995@gmail.com'], fail_silently=False)
    return render(request, 'home/me.html', {})
    
	


def post_list(request):
    query =  request.GET.get("q")
    posts_seta = Post.objects.all().order_by('-created')
    posts_setb = Post.objects.all().order_by('-created')
    tagi = Tag.objects.all()
    if query:
        posts_seta= posts_seta.filter(Q(title = query)|Q(author = query)|Q(text = query)).distinct()
    

    paginator = Paginator(posts_seta,2)
    page = request.GET.get('page')
    
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        posts = paginator.page(paginator.num_pages)

    return render(request, 'home/index.html', {'posts': posts,'posts_setb': posts_setb,'tagi': tagi})


def post_tagdetail(request,tag_field):
    
    posts = Post.objects.all
    return render(request, 'home/post_tagdetail.html', {'posts': posts, 'tag_field':tag_field})


















def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'home/post_detail.html', {'post': post})
#     if request.method == "POST":
#         form = PostForm(request.POST)
#         if form.is_valid():
#             post = form.save(commit=False)
#             post.save()
            
#     else:
#         form = PostForm()
#     return render(request, 'home/post_detail.html', {'form': form ,'post': post})






# def post_new(request):
#     if request.method == "POST":
#         form = PostForm(request.POST)
#         if form.is_valid():
#             post = form.save(commit=False)
#             post.save()
            
#     else:
#         form = PostForm()
#     return render(request, 'home/post_detail.html', {'form': form})






# Create your views here.

resume/views.py
from django.shortcuts import render

from django.shortcuts import render, get_object_or_404


def me(request):
	return render(request, 'home/me.html', {})


# Create your views here.

contact/templates/contact/contact.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Glimpse Of Hope</title>

    <!-- Bootstrap Core CSS -->

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/clean-blog.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>


<style>


#btn-default{
	color:#000000;
}
#id_email_id{
	z-index: 1;
    position: relative;
    padding-right: 0;
    padding-left: 0;
    border: none;
    border-radius: 0;
    font-size: 1.5em;
    background: none;
    box-shadow: none !important;
    resize: none;
    font-size: 20px;
    position: relative;
    margin-bottom: 0;
    padding-bottom: 0.5em;
    border-bottom: 1px solid #eeeeee;
    display: block;
    width: 100%;
    height: 34px;
    padding: 6px 12px;
    font-size: 14px;
    line-height: 1.42857143;
    background-color: #000;
    color: #fff;
    background-image: none;
    border-radius: 4px;
    
    }


#id_text{
	z-index: 1;
    position: relative;
    padding-right: 0;
    padding-left: 0;
    border: none;
    border-radius: 0;
    font-size: 1.5em;
    background: none;
    box-shadow: none !important;
    resize: none;
    font-size: 20px;
    position: relative;
    margin-bottom: 0;
    padding-bottom: 0.5em;
    border-bottom: 1px solid #eeeeee;
    display: block;
    width: 100%;
    /*height: 34px;*/
    padding: 6px 12px;
    font-size: 14px;
    line-height: 1.42857143;
    background-color: #000;
    color: #fff;
    background-image: none;
    border-radius: 4px;
    
    }
    #id_name{
	z-index: 1;
    position: relative;
    padding-right: 0;
    padding-left: 0;
    border: none;
    border-radius: 0;
    font-size: 1.5em;
    background: none;
    box-shadow: none !important;
    resize: none;
    font-size: 20px;
    position: relative;
    margin-bottom: 0;
    padding-bottom: 0.5em;
    border-bottom: 1px solid #eeeeee;
    display: block;
    width: 100%;
    /*height: 34px;*/
    padding: 6px 12px;
    font-size: 14px;
    line-height: 1.42857143;
    background-color: #000;
    color: #fff;
    background-image: none;
    border-radius: 4px;
    
    }

</style>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->


</head>

<body>


<nav class="navbar navbar-default navbar-custom navbar-fixed-top" style= "background-color:#000000">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">Gimpse Of Hope</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1" style = "background-color:#000000">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="/">Home</a>
                    </li>
                    <li>
                        <a href="/me">About</a>
                    </li>
                   
                    <li>
                        <a href="#">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-color:#000000">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="page-heading">
                        <h1>Contact Me</h1>
                        <hr class="small">
                        <span class="subheading">Have questions? I have answers (maybe).</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <p>Want to get in touch with me? Fill out the form below to send me a message and I will try to get back to you within 24 hours!</p>
           







                    <br>
                    <div id="success"></div>
                     
                    <div class="row">
                        <div class="form-group col-xs-12">
                          
<form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
                        </div>
                    </div>
                
            </div>
        </div>
    </div>

    <hr>

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                       </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; Your Website 2014</p>
                </div>
            </div>
        </div>
    </footer>

     <script src="{% static 'js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{% static 'js/clean-blog.min.js' %}"></script>


</body>

</html>

home/templates/home/ds.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>GLIMPSE OF FUTURE</title>

    <!-- Bootstrap Core CSS -->

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/clean-blog.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

   <style>
/*button {
  color: #900;
  font-weight: bold;
}*/


   </style>

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top" style = "background-color:#000000">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll"style = "background-color:#000000">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">DJANDROID!!</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="/">Home</a>
                    </li>
                    <li>
                        <a href="/me">About</a>
                    </li>
                    
                    <li>
                        <a href="/contact">Contact</a>
                    </li>

                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
<br><br
>
    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
     <div class="container">
    <header class="intro-header" style="background-image: url('{% static 'img/home-ds.jpg' %}')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                       
                    </div>
                </div>
            </div>
        </div>
    </header>
</div>

    <!-- Main Content -->

    <div class="container">
        <div class="row">
            <div class="col-lg-12 ">
         <div class="post-preview">
<center><h1 style = "color:#000000"><span class="glyphicon glyphicon-star-empty" aria-hidden="true"></span>&nbsp;<u>FEATURED POSTS</u>&nbsp;<span class="glyphicon glyphicon-star-empty" aria-hidden="true"></span></h1></center></br>
            {% for post in posts_setb %}
            {% if post.draft = False %}
            {% if post.featured %}
               
                
              
                    <a href="{% url 'post_detail' pk=post.pk %}">
                        <h1 class="post-title" style="color:black">
                            <span class="glyphicon glyphicon-star" aria-hidden="true"></span> &nbsp;{{post.title}}
                        </h1>  </a>
                         <h5 >{%for tag in post.tag_field.all%}
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{tag.title_tag}}
                        {%endfor%}</h5>
                        <h4 class="post-subtitle">
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{post.text}}
                        </h4>
                                    

                  
                    <p class="post-meta">
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Posted by &nbsp;<b>{{post.author}}</b>&nbsp; on {{post.created}}</p>
  
{% endif %}
{% endif %}
{% endfor %}                       
                </div>
            </div>
             
            </div>    
            </div>   


<!-- 
            <div class="container">
                <div class="row"style="background-image: url('{% static 'img/home-bg.jpg' %}');height:200px">
                    <center>
                        
                        <a href=""></a> <img src="{% static 'img/home-ds.jpg' %}"  alt="Cinque Terre"  height="400px"></a>

                        
                    </center></br>
                </div>
            </div>
 -->


        <section id = "olderposts">
            <a id="relocate" href="#OlderPost"></a>
            <div class="container">
                <div class="row">
                    <center>
                        <div id="OlderPost">
                            <h1 style = "color:#000000"><u>OLDER POSTS</u></h1>
                        </div>
                    </center></br>
                        
<div class="container">

<div class="btn-group btn-group-justified" role="group" aria-label="...">
  <div class="btn-group" role="group">
    <a href="{% url 'post_tagdetail' tag_field='POVERTY' %}">
         <button type="button" class="btn btn-default">Poverty</button>
    </a>
</a>
  </div>
  
  <div class="btn-group" role="group">
     <a href="{% url 'post_tagdetail' tag_field='EDUCATION' %}">
    <button type="button" class="btn btn-default">#Education</button>
    </a>
  </div>
  
  <div class="btn-group" role="group">
    <a href="{% url 'post_tagdetail' tag_field='ABUSE' %}">
    <button type="button" class="btn btn-default">#Abuse</button>
     </a>
  </div>
  <div class="btn-group" role="group">
        <a href="{% url 'post_tagdetail' tag_field='ILLITERACY' %}">
    <button type="button" class="btn btn-default">#Illiteracy</button>

     </a>
  </div>
</div>


<div class="btn-group btn-group-justified" role="group" aria-label="...">
  <div class="btn-group" role="group">
     <a href="{% url 'post_tagdetail' tag_field='CORRUPTION' %}">
    <button type="button" class="btn btn-default">#Corruption</button>
    </a>

  </div>
  <div class="btn-group" role="group">
     <a href="{% url 'post_tagdetail' tag_field='DRUGABUSE' %}">
    <button type="button" class="btn btn-default">#Drug Abuse</button>
    </a>

  </div>
  <div class="btn-group" role="group">
     <a href="{% url 'post_tagdetail' tag_field='EDUCATION' %}">
    <button type="button" class="btn btn-default">#Child Labour</button>
    </a>

  </div>
</div>




<div class="btn-group btn-group-justified" role="group" aria-label="...">
  <div class="btn-group" role="group">
     <a href="{% url 'post_tagdetail' tag_field='EDUCATION' %}">
    <button type="button" class="btn btn-default">#Casteism</button>
    </a>

  </div>
  <div class="btn-group" role="group">
     <a href="{% url 'post_tagdetail' tag_field='EDUCATION' %}">
    <button type="button" class="btn btn-default">#Crime</button>
</a>
  </div>
  
</div>

<br>
<div class="row">

<form  method = 'GET' action = ''>
    <div class ="col-xs-8 col-md-8">
    <input id="searchbar" type = 'text' class="form-control" name = 'q' placeholder = 'Search Post' value = '{{request.GET.q}}' style ="width:100%;"/>
    </div>
    <div class ="col-xs-4 col-md-4">
    <input type = 'submit' class="form-control" value = 'Search'  style ="width:100%;color:#fff;background-color:#000"/>
    </div>

</form>
</div>

</div>




<div class = "row">
            <div class="col-lg-12 ">
         <div class="post-preview">
            {% for post in posts %}
            {% if post.featured = False %}
               {% if post.draft = False %}
                           


                    <a href="{% url 'post_detail' pk=post.pk %}">
                        <h2 class="post-title" style="color:black">
                            <span class="glyphicon glyphicon-grain" aria-hidden="true"></span> &nbsp;{{post.title}}
                        </h2>
                        <h3 class="post-subtitle">
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{post.text}}
                        </h3>
                        <h5 >{%for tag in post.tag_field.all%}
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{tag.title_tag}}
                        {%endfor%}</h5>
                    </a>
                    <p class="post-meta">
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Posted by &nbsp;<b>{{post.author}}</b>&nbsp; on {{post.created}}</p>

{% endif %}

{% endif %}
{% endfor %} 
                </div>
            
               
            
       


       <div class="pagination">
    <span class="step-links">
        <h2>
        {% if posts.has_previous %}
            <a href="?page={{ posts.previous_page_number }}{% if request.GET.q %}&q={{request.GET.q}}{% endif %}#olderposts"><i class="fa fa-chevron-circle-left"></i></a>
        {% endif %}

        <span class="current">
            Page {{ posts.number }} of {{ posts.paginator.num_pages }}
        </span>

        {% if posts.has_next %}
            <a href="?page={{ posts.next_page_number }}{% if request.GET.q %}&q={{request.GET.q}}{% endif %}#olderposts"><i class="fa fa-chevron-circle-right"></i></a>
        {% endif %}
        </h2>
    </span>
</div> 
 </div>
  </div>
 </section>

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                       
                        <li>
                            <a href="https://www.facebook.com/sarthak.dargan">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="https://github.com/sarthak221995">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; GLIMPSE OF FUTURE 2016</p>


                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="{% static 'js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{% static 'js/clean-blog.min.js' %}"></script>
    <!-- 
    <script type="text/javascript">
        $(document).ready(function () {
            console.log("here");
            console.log($("#relocate"));
            $('#relocate')[0].click();
        });

        $("#OlderPost").on("click", function () {
            console.log("FIred");
        });
    </script>
 -->
</body>

</html>